package com.valvesoftware.vr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.ShortByReference;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RenderModel_t extends Structure {
	/** Used internally by SteamVR */
	public long ulInternalHandle;
	/** Vertex data for the mesh */
	public com.valvesoftware.vr.RenderModel_Vertex_t.ByReference rVertexData;
	/** Number of vertices in the vertex data */
	public int unVertexCount;
	/** Indices into the vertex data for each triangle */
	public ShortByReference rIndexData;
	/** Number of triangles in the mesh. Index count is 3 * TriangleCount */
	public int unTriangleCount;
	/** RGBA diffuse texture for the model */
	public RenderModel_TextureMap_t diffuseTexture;
	public RenderModel_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ulInternalHandle", "rVertexData", "unVertexCount", "rIndexData", "unTriangleCount", "diffuseTexture");
	}
	public RenderModel_t(long ulInternalHandle, com.valvesoftware.vr.RenderModel_Vertex_t.ByReference rVertexData, int unVertexCount, ShortByReference rIndexData, int unTriangleCount, RenderModel_TextureMap_t diffuseTexture) {
		super();
		this.ulInternalHandle = ulInternalHandle;
		this.rVertexData = rVertexData;
		this.unVertexCount = unVertexCount;
		this.rIndexData = rIndexData;
		this.unTriangleCount = unTriangleCount;
		this.diffuseTexture = diffuseTexture;
	}
	public RenderModel_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends RenderModel_t implements Structure.ByReference {
		
	};
	public static class ByValue extends RenderModel_t implements Structure.ByValue {
		
	};
}
